#!/usr/bin/env python3
"""Generate the deterministic, conflict-safe Playerbot SQL seed."""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path


BOT_COUNT = 1500
FIRST_PID = 4
SEED_VERSION = 1

# This is the canonical local cohort used by the earlier 450-bot bootstrap.
# Keeping the compact recipe here makes a clean clone independent of a live DB.
NAME_PREFIXES = (
    "dariusz", "arek", "brutus", "cien", "luk", "mrok", "runia", "iskra",
    "grom", "probe", "valkyrie", "shadow", "viper", "phantom", "witch", "blaze",
    "storm", "titan", "glory", "ghost", "raven", "abyss", "mystic", "oracle",
    "sun", "knight", "blade", "dusk", "silent", "chaos", "void", "nova",
    "frost", "inferno", "echo", "specter", "draco", "saber", "fury", "zenith",
    "onyx", "scarlet", "silver", "amber", "jade", "coral", "flint", "iron",
    "steel", "talon", "fang", "claw", "hawk", "falcon", "eagle", "wolf",
    "lynx", "panther", "tiger", "bear", "lion", "cobra", "hydra", "chimera",
)
JOBS = (0, 4, 1, 5, 2, 6, 3, 7)
STATS = {
    0: (760, 260, 6, 4, 3, 3),
    4: (760, 260, 6, 4, 3, 3),
    1: (770, 260, 4, 3, 6, 3),
    5: (770, 260, 4, 3, 6, 3),
    2: (770, 300, 5, 3, 3, 5),
    6: (770, 300, 5, 3, 3, 5),
    3: (860, 320, 3, 4, 3, 6),
    7: (860, 320, 3, 4, 3, 6),
}


def cohort() -> list[dict[str, int | str]]:
    rows: list[dict[str, int | str]] = []
    for ordinal in range(1, BOT_COUNT + 1):
        prefix = NAME_PREFIXES[(ordinal - 1) % len(NAME_PREFIXES)]
        cycle = (ordinal - 1) // len(NAME_PREFIXES)
        suffix = "" if cycle == 0 else str(cycle + 1)
        job = JOBS[(ordinal - 1) % len(JOBS)]
        hp, mp, st, ht, dx, iq = STATS[job]
        rows.append(
            {
                "pid": FIRST_PID + ordinal - 1,
                "login": f"playerbot_{ordinal:03d}",
                "social_id": f"9{ordinal:012d}",
                "name": f"bot{prefix}{suffix}",
                "job": job,
                "x": 51000 + ((ordinal - 1) % 25) * 80,
                "y": 165000 + ((ordinal - 1) // 25) * 120,
                "hp": hp,
                "mp": mp,
                "st": st,
                "ht": ht,
                "dx": dx,
                "iq": iq,
            }
        )
    validate(rows)
    return rows


def validate(rows: list[dict[str, int | str]]) -> None:
    pids = [int(row["pid"]) for row in rows]
    names = [str(row["name"]) for row in rows]
    logins = [str(row["login"]) for row in rows]
    socials = [str(row["social_id"]) for row in rows]

    expected_pids = list(range(FIRST_PID, FIRST_PID + BOT_COUNT))
    if len(rows) != BOT_COUNT or pids != expected_pids:
        raise ValueError("cohort must contain exactly PID %d..%d in order"
                         % (FIRST_PID, FIRST_PID + BOT_COUNT - 1))
    for label, values in (("name", names), ("login", logins), ("social_id", socials)):
        if len(values) != len(set(values)):
            raise ValueError(f"cohort has duplicate {label}")
    if any(len(name.encode("ascii")) > 24 for name in names):
        raise ValueError("a bot name exceeds player.name varchar(24)")
    if any(len(login.encode("ascii")) > 30 for login in logins):
        raise ValueError("a bot login exceeds account.login varchar(30)")
    if any(len(social) != 13 or not social.isascii() or not social.isdigit() for social in socials):
        raise ValueError("social IDs must be unique 13-digit ASCII strings")
    if any(int(row["job"]) not in range(8) for row in rows):
        raise ValueError("job must be in the r40250 range 0..7")


def sql_quote(value: object) -> str:
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


def render_sql(rows: list[dict[str, int | str]]) -> str:
    values = []
    columns = (
        "pid", "login", "social_id", "name", "job", "x", "y",
        "hp", "mp", "st", "ht", "dx", "iq",
    )
    string_columns = {"login", "social_id", "name"}
    for row in rows:
        rendered = [sql_quote(row[column]) if column in string_columns else str(row[column]) for column in columns]
        values.append("    (" + ", ".join(rendered) + ")")

    sql = r"""-- Generated by linux-port/overlays/playerbot/tools/generate_seed.py.
-- DO NOT EDIT: run the generator, then run it again with --check.
--
-- Canonical Playerbot cohort: explicit, contiguous player PIDs from 4 upwards.
-- Fresh accounts are non-login accounts: unique login/social ID, password '!'
-- and status BLOCK. Existing matching bots are adopted without changing any
-- gameplay state. Any foreign PID/name/account/index collision aborts before
-- durable changes; the Compose wrapper decides whether that is warning-only or
-- fatal according to PLAYERBOT_SEED_STRICT.

SET NAMES latin1;
USE player;

DROP TEMPORARY TABLE IF EXISTS playerbot_seed_spec;
CREATE TEMPORARY TABLE playerbot_seed_spec (
    pid         INT UNSIGNED NOT NULL,
    login       VARCHAR(30) NOT NULL,
    social_id   VARCHAR(13) NOT NULL,
    player_name VARCHAR(24) NOT NULL,
    job         TINYINT UNSIGNED NOT NULL,
    x           INT NOT NULL,
    y           INT NOT NULL,
    hp          SMALLINT NOT NULL,
    mp          SMALLINT NOT NULL,
    st          SMALLINT NOT NULL,
    ht          SMALLINT NOT NULL,
    dx          SMALLINT NOT NULL,
    iq          SMALLINT NOT NULL,
    PRIMARY KEY (pid),
    UNIQUE KEY uq_playerbot_seed_login (login),
    UNIQUE KEY uq_playerbot_seed_social (social_id),
    UNIQUE KEY uq_playerbot_seed_name (player_name)
) ENGINE=MEMORY DEFAULT CHARSET=latin1;

INSERT INTO playerbot_seed_spec
    (pid, login, social_id, player_name, job, x, y, hp, mp, st, ht, dx, iq)
VALUES
@@VALUES@@;

-- The generated registry describes itself; validate that before looking at a
-- single durable row.
DELIMITER //
BEGIN NOT ATOMIC
    DECLARE v_count INT DEFAULT 0;
    DECLARE v_min_pid INT DEFAULT 0;
    DECLARE v_max_pid INT DEFAULT 0;

    SELECT COUNT(*), COALESCE(MIN(pid), 0), COALESCE(MAX(pid), 0)
      INTO v_count, v_min_pid, v_max_pid
      FROM playerbot_seed_spec;
    IF v_count <> @@COUNT@@ OR v_min_pid <> @@FIRST@@ OR v_max_pid <> @@LAST@@ THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed: registry is not exactly PID @@FIRST@@..@@LAST@@';
    END IF;

    -- The skip rules below read this ledger, so it is created here rather than
    -- halfway through the durable-state pass. It is empty and idempotent;
    -- creating it early commits to nothing.
    CREATE TABLE IF NOT EXISTS common.playerbot_seed_state (
        pid          INT UNSIGNED NOT NULL,
        seed_version SMALLINT UNSIGNED NOT NULL,
        state        ENUM('pending','complete','adopted') NOT NULL,
        updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                     ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (pid)
    ) ENGINE=MyISAM DEFAULT CHARSET=ascii;
END//
DELIMITER ;

-- Every reason a PID must be left alone. Each of these used to abort the whole
-- seed, so a single renamed bot froze a world at whatever cohort it happened to
-- have: the launcher offered more bots and the database never grew to hold
-- them. A PID that is not ours is now dropped from the registry instead, and
-- the rest are still created. Nothing here updates or deletes a durable row,
-- and the checks further down keep their SIGNAL - they are assertions now, so
-- the worst case is exactly the behaviour this replaces.
DROP TEMPORARY TABLE IF EXISTS playerbot_seed_skip;
-- Deliberately no unique key: a PID usually trips several of the rules below,
-- and a PRIMARY KEY turned each repeat into a duplicate-entry warning. Two
-- thousand of those in front of an operator, for a table whose only job is to
-- collect names, is worse than useless - it buries the two lines that matter.
CREATE TEMPORARY TABLE playerbot_seed_skip (
    pid INT UNSIGNED NOT NULL,
    KEY (pid)
) ENGINE=MEMORY DEFAULT CHARSET=latin1;

-- Renamed, re-classed, or otherwise not the character this registry describes.
INSERT INTO playerbot_seed_skip (pid)
SELECT s.pid
  FROM playerbot_seed_spec AS s
  JOIN player.player AS p ON p.id = s.pid
 WHERE BINARY p.name <> BINARY s.player_name OR p.job <> s.job;

-- player.name is only indexed, not unique, so aliases need their own pass.
INSERT INTO playerbot_seed_skip (pid)
SELECT s.pid
  FROM playerbot_seed_spec AS s
  JOIN player.player AS p ON p.name = s.player_name
 WHERE p.id <> s.pid;

-- An existing character sitting on a foreign account.
INSERT INTO playerbot_seed_skip (pid)
SELECT s.pid
  FROM playerbot_seed_spec AS s
  JOIN player.player AS p ON p.id = s.pid
  LEFT JOIN account.account AS a ON a.id = p.account_id
 WHERE a.id IS NULL
    OR BINARY a.login <> BINARY s.login
    OR BINARY a.social_id <> BINARY s.social_id;

-- The canonical login already owns somebody else.
INSERT INTO playerbot_seed_skip (pid)
SELECT s.pid
  FROM playerbot_seed_spec AS s
  JOIN account.account AS a ON a.login = s.login
  JOIN player.player AS p ON p.account_id = a.id
 WHERE p.id <> s.pid;

-- The canonical social ID is attached to a different login.
INSERT INTO playerbot_seed_skip (pid)
SELECT s.pid
  FROM playerbot_seed_spec AS s
  JOIN account.account AS a ON a.social_id = s.social_id
 WHERE BINARY a.login <> BINARY s.login;

-- A missing PID may resume a pre-existing account only when that account is
-- unmistakably an unused partial result of this seed.
INSERT INTO playerbot_seed_skip (pid)
SELECT s.pid
  FROM playerbot_seed_spec AS s
  JOIN account.account AS a ON a.login = s.login
  LEFT JOIN player.player AS p ON p.account_id = a.id
  LEFT JOIN player.player_index AS pi ON pi.id = a.id
 WHERE NOT EXISTS (SELECT 1 FROM player.player AS pe WHERE pe.id = s.pid)
   AND (BINARY a.social_id <> BINARY s.social_id
        OR BINARY a.password <> BINARY '!'
        OR BINARY a.status <> BINARY 'BLOCK'
        OR p.id IS NOT NULL
        OR pi.id IS NOT NULL);

-- The canonical account carries an index that is not the expected single
-- Chunjo character.
INSERT INTO playerbot_seed_skip (pid)
SELECT s.pid
  FROM playerbot_seed_spec AS s
  JOIN player.player AS p ON p.id = s.pid
  JOIN account.account AS a ON a.id = p.account_id
  LEFT JOIN player.player_index AS pi ON pi.id = a.id
 WHERE pi.id IS NOT NULL
   AND (pi.pid1 <> s.pid OR pi.pid2 <> 0 OR pi.pid3 <> 0 OR pi.pid4 <> 0
        OR pi.empire <> 2);

-- The PID is referenced by somebody else's index slot.
INSERT INTO playerbot_seed_skip (pid)
SELECT s.pid
  FROM playerbot_seed_spec AS s
  JOIN player.player_index AS pi
    ON s.pid IN (pi.pid1, pi.pid2, pi.pid3, pi.pid4)
  LEFT JOIN account.account AS a ON a.login = s.login
  LEFT JOIN player.player AS p ON p.id = s.pid
 WHERE p.id IS NULL
    OR a.id IS NULL
    OR pi.id <> a.id
    OR pi.pid1 <> s.pid
    OR pi.pid2 <> 0 OR pi.pid3 <> 0 OR pi.pid4 <> 0
    OR pi.empire <> 2;

-- Ledger rows from another seed version, or completed rows whose character is
-- gone, are ambiguous and must be repaired by an operator rather than guessed.
INSERT INTO playerbot_seed_skip (pid)
SELECT s.pid
  FROM playerbot_seed_spec AS s
  JOIN common.playerbot_seed_state AS l ON l.pid = s.pid
  LEFT JOIN player.player AS p ON p.id = s.pid
 WHERE l.seed_version <> 1
    OR (p.id IS NULL AND l.state IN ('complete', 'adopted'));

SELECT CONCAT('playerbot seed: preserving ', COUNT(DISTINCT pid),
              ' existing character(s) untouched') AS playerbot_seed_note
  FROM playerbot_seed_skip;

DELETE FROM playerbot_seed_spec WHERE pid IN (SELECT pid FROM playerbot_seed_skip);

DROP TEMPORARY TABLE IF EXISTS playerbot_seed_missing;
CREATE TEMPORARY TABLE playerbot_seed_missing LIKE playerbot_seed_spec;
INSERT INTO playerbot_seed_missing
SELECT s.*
FROM playerbot_seed_spec AS s
LEFT JOIN player.player AS p ON p.id = s.pid
WHERE p.id IS NULL;

SELECT CONCAT('playerbot seed: creating ', COUNT(*),
              ' new bot character(s)') AS playerbot_seed_note
  FROM playerbot_seed_missing;

DELIMITER //
BEGIN NOT ATOMIC
    DECLARE v_count INT DEFAULT 0;
    DECLARE v_expected INT DEFAULT 0;
    DECLARE v_conflicts INT DEFAULT 0;

    -- A target PID may be reused only when its immutable identity is exact.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN player.player AS p ON p.id = s.pid
     WHERE BINARY p.name <> BINARY s.player_name OR p.job <> s.job;
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: target PID has a foreign name or job';
    END IF;

    -- player.name is only indexed, not unique, so detect aliases explicitly.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN player.player AS p ON p.name = s.player_name
     WHERE p.id <> s.pid;
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: expected name belongs to another PID';
    END IF;

    -- Existing bots must already belong to their canonical account. Password,
    -- status and all gameplay fields are deliberately not normalized on update.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN player.player AS p ON p.id = s.pid
      LEFT JOIN account.account AS a ON a.id = p.account_id
     WHERE a.id IS NULL
        OR BINARY a.login <> BINARY s.login
        OR BINARY a.social_id <> BINARY s.social_id;
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: existing PID has a foreign account';
    END IF;

    -- One bot account owns one character. Never attach a new bot to an account
    -- that already owns another character.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN account.account AS a ON a.login = s.login
      JOIN player.player AS p ON p.account_id = a.id
     WHERE p.id <> s.pid;
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: expected login owns another player';
    END IF;

    -- social_id has no UNIQUE constraint in the shipped schema.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN account.account AS a ON a.social_id = s.social_id
     WHERE BINARY a.login <> BINARY s.login;
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: social ID belongs to another login';
    END IF;

    -- A pre-existing account may be resumed for a missing PID only when it is
    -- unmistakably an unused partial result of this seed.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_missing AS s
      JOIN account.account AS a ON a.login = s.login
      LEFT JOIN player.player AS p ON p.account_id = a.id
      LEFT JOIN player.player_index AS pi ON pi.id = a.id
     WHERE BINARY a.login <> BINARY s.login
        OR BINARY a.social_id <> BINARY s.social_id
        OR BINARY a.password <> BINARY '!'
        OR BINARY a.status <> BINARY 'BLOCK'
        OR p.id IS NOT NULL
        OR pi.id IS NOT NULL;
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: missing PID account is foreign';
    END IF;

    -- Existing index rows may be absent (they will be added), or must be the
    -- exact one-character Chunjo index expected by the canonical account.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN player.player AS p ON p.id = s.pid
      JOIN account.account AS a ON a.id = p.account_id
      LEFT JOIN player.player_index AS pi ON pi.id = a.id
     WHERE pi.id IS NOT NULL
       AND (pi.pid1 <> s.pid OR pi.pid2 <> 0 OR pi.pid3 <> 0 OR pi.pid4 <> 0 OR pi.empire <> 2);
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: canonical account has a foreign index';
    END IF;

    -- Also reject a target PID referenced by any other/stale index slot.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN player.player_index AS pi
        ON s.pid IN (pi.pid1, pi.pid2, pi.pid3, pi.pid4)
      LEFT JOIN account.account AS a ON a.login = s.login
      LEFT JOIN player.player AS p ON p.id = s.pid
     WHERE p.id IS NULL
        OR a.id IS NULL
        OR pi.id <> a.id
        OR pi.pid1 <> s.pid
        OR pi.pid2 <> 0 OR pi.pid3 <> 0 OR pi.pid4 <> 0
        OR pi.empire <> 2;
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: target PID is in a foreign index';
    END IF;

    -- Only now is it safe to create durable migration metadata. MyISAM does
    -- not roll back, so this ledger lets an interrupted first seed finish only
    -- missing starter slots. Adopted/complete bots are never restocked.
    CREATE TABLE IF NOT EXISTS common.playerbot_seed_state (
        pid          INT UNSIGNED NOT NULL,
        seed_version SMALLINT UNSIGNED NOT NULL,
        state        ENUM('pending','complete','adopted') NOT NULL,
        updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                     ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (pid)
    ) ENGINE=MyISAM DEFAULT CHARSET=ascii;

    -- Ledger rows from another seed version, or completed rows whose player is
    -- gone, are ambiguous and must be repaired by an operator rather than guessed.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN common.playerbot_seed_state AS l ON l.pid = s.pid
      LEFT JOIN player.player AS p ON p.id = s.pid
     WHERE l.seed_version <> 1
        OR (p.id IS NULL AND l.state IN ('complete', 'adopted'));
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: ledger conflicts with player data';
    END IF;

    -- Mark every previously unseen row before touching MyISAM account/player
    -- data. A crash from here on leaves a resumable pending marker.
    INSERT INTO common.playerbot_seed_state (pid, seed_version, state)
    SELECT s.pid, 1, IF(p.id IS NULL, 'pending', 'adopted')
      FROM playerbot_seed_spec AS s
      LEFT JOIN player.player AS p ON p.id = s.pid
      LEFT JOIN common.playerbot_seed_state AS l ON l.pid = s.pid
     WHERE l.pid IS NULL;

    INSERT INTO account.account
        (login, password, social_id, email, create_time, is_testor, status,
         empire, name_checked, availDt, last_play)
    SELECT s.login, '!', s.social_id, '', UTC_TIMESTAMP(), 0, 'BLOCK',
           2, 1, UTC_TIMESTAMP(), UTC_TIMESTAMP()
      FROM playerbot_seed_missing AS s
      JOIN common.playerbot_seed_state AS l ON l.pid = s.pid AND l.state = 'pending'
      LEFT JOIN account.account AS a ON a.login = s.login
     WHERE a.id IS NULL;

    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_missing AS s
      LEFT JOIN account.account AS a ON a.login = s.login
     WHERE a.id IS NULL
        OR BINARY a.login <> BINARY s.login
        OR BINARY a.social_id <> BINARY s.social_id
        OR BINARY a.password <> BINARY '!'
        OR BINARY a.status <> BINARY 'BLOCK';
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed: failed to create blocked bot accounts';
    END IF;

    INSERT INTO player.player
        (id, account_id, name, job, voice, dir, x, y, z, map_index,
         exit_x, exit_y, exit_map_index, hp, mp, stamina, level, level_step,
         st, ht, dx, iq, exp, gold, stat_point, skill_point, skill_group,
         sub_skill_point, stat_reset_count, horse_hp, horse_stamina,
         horse_level, horse_hp_droptime, horse_riding, horse_skill_point,
         bank_value, last_play)
    SELECT s.pid, a.id, s.player_name, s.job, 0, 0, s.x, s.y, 0, 21,
           s.x, s.y, 21, s.hp, s.mp, 800, 1, 0,
           s.st, s.ht, s.dx, s.iq, 0, 2500, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, UTC_TIMESTAMP()
      FROM playerbot_seed_missing AS s
      JOIN account.account AS a ON a.login = s.login
      JOIN common.playerbot_seed_state AS l ON l.pid = s.pid AND l.state = 'pending'
      LEFT JOIN player.player AS p ON p.id = s.pid
     WHERE p.id IS NULL;

    -- Adding a genuinely missing index is safe for adopted bots as well; no
    -- existing row is ever updated or reassigned.
    INSERT INTO player.player_index (id, pid1, pid2, pid3, pid4, empire)
    SELECT a.id, s.pid, 0, 0, 0, 2
      FROM playerbot_seed_spec AS s
      JOIN player.player AS p
        ON p.id = s.pid AND BINARY p.name = BINARY s.player_name AND p.job = s.job
      JOIN account.account AS a
        ON a.id = p.account_id
       AND BINARY a.login = BINARY s.login
       AND BINARY a.social_id = BINARY s.social_id
      LEFT JOIN player.player_index AS pi ON pi.id = a.id
     WHERE pi.id IS NULL;

    DROP TEMPORARY TABLE IF EXISTS playerbot_seed_pending;
    CREATE TEMPORARY TABLE playerbot_seed_pending (
        pid INT UNSIGNED NOT NULL PRIMARY KEY
    ) ENGINE=MEMORY;
    INSERT INTO playerbot_seed_pending (pid)
    SELECT s.pid
      FROM playerbot_seed_spec AS s
      JOIN common.playerbot_seed_state AS l ON l.pid = s.pid
     WHERE l.state = 'pending';

    -- Only pending (new or interrupted) bots receive starter slots. An occupied
    -- slot is preserved, regardless of which item is already there.
    INSERT INTO player.item (owner_id, window, pos, count, vnum)
    SELECT s.pid, 'EQUIPMENT', 4, 1,
           CASE
             WHEN s.job IN (0, 2, 4, 6) THEN 10
             WHEN s.job IN (1, 5) THEN 1000
             WHEN s.job IN (3, 7) THEN 7000
           END
      FROM playerbot_seed_spec AS s
      JOIN playerbot_seed_pending AS q ON q.pid = s.pid
      LEFT JOIN player.item AS i
        ON i.owner_id = s.pid AND i.window = 'EQUIPMENT' AND i.pos = 4
     WHERE i.id IS NULL;

    INSERT INTO player.item (owner_id, window, pos, count, vnum)
    SELECT s.pid, 'EQUIPMENT', 0, 1,
           CASE
             WHEN s.job IN (0, 4) THEN 11200
             WHEN s.job IN (1, 5) THEN 11400
             WHEN s.job IN (2, 6) THEN 11600
             WHEN s.job IN (3, 7) THEN 11800
           END
      FROM playerbot_seed_spec AS s
      JOIN playerbot_seed_pending AS q ON q.pid = s.pid
      LEFT JOIN player.item AS i
        ON i.owner_id = s.pid AND i.window = 'EQUIPMENT' AND i.pos = 0
     WHERE i.id IS NULL;

    INSERT INTO player.item (owner_id, window, pos, count, vnum)
    SELECT s.pid, 'INVENTORY', 0, 200, 27001
      FROM playerbot_seed_spec AS s
      JOIN playerbot_seed_pending AS q ON q.pid = s.pid
      LEFT JOIN player.item AS i
        ON i.owner_id = s.pid AND i.window = 'INVENTORY' AND i.pos = 0
     WHERE i.id IS NULL;

    INSERT INTO player.item (owner_id, window, pos, count, vnum)
    SELECT s.pid, 'INVENTORY', 1, 200, 27004
      FROM playerbot_seed_spec AS s
      JOIN playerbot_seed_pending AS q ON q.pid = s.pid
      LEFT JOIN player.item AS i
        ON i.owner_id = s.pid AND i.window = 'INVENTORY' AND i.pos = 1
     WHERE i.id IS NULL;

    INSERT INTO player.item (owner_id, window, pos, count, vnum)
    SELECT s.pid, 'INVENTORY', 2, 1,
           CASE
             WHEN s.job IN (0, 2, 4, 6) THEN 50187
             WHEN s.job IN (1, 5) THEN 50212
             WHEN s.job IN (3, 7) THEN 50213
           END
      FROM playerbot_seed_spec AS s
      JOIN playerbot_seed_pending AS q ON q.pid = s.pid
      LEFT JOIN player.item AS i
        ON i.owner_id = s.pid AND i.window = 'INVENTORY' AND i.pos = 2
     WHERE i.id IS NULL;

    -- The seed already supplied the starter chest above. Mark the stock login
    -- reward as claimed so give_basic_weapon does not create a second chest and,
    -- transitively, duplicate every later Apprentice/Expert chest.
    INSERT INTO player.quest (dwPID, szName, szState, lValue)
    SELECT q.pid, 'give_basic_weapon', 'basic_weapon', 1
      FROM playerbot_seed_pending AS q
    ON DUPLICATE KEY UPDATE lValue = GREATEST(lValue, VALUES(lValue));

    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_pending AS q
     WHERE NOT EXISTS (
               SELECT 1 FROM player.item AS i
                WHERE i.owner_id = q.pid AND i.window = 'EQUIPMENT' AND i.pos = 4)
        OR NOT EXISTS (
               SELECT 1 FROM player.item AS i
                WHERE i.owner_id = q.pid AND i.window = 'EQUIPMENT' AND i.pos = 0)
        OR NOT EXISTS (
               SELECT 1 FROM player.item AS i
                WHERE i.owner_id = q.pid AND i.window = 'INVENTORY' AND i.pos = 0)
        OR NOT EXISTS (
               SELECT 1 FROM player.item AS i
                WHERE i.owner_id = q.pid AND i.window = 'INVENTORY' AND i.pos = 1)
        OR NOT EXISTS (
               SELECT 1 FROM player.item AS i
                WHERE i.owner_id = q.pid AND i.window = 'INVENTORY' AND i.pos = 2);
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed: starter slots are incomplete';
    END IF;

    UPDATE common.playerbot_seed_state AS l
      JOIN playerbot_seed_pending AS q ON q.pid = l.pid
       SET l.state = 'complete', l.seed_version = 1;

    -- Final structural assertion; this intentionally does not compare level,
    -- position, skills, horse, quests, gold or items of adopted bots.
    SELECT COUNT(*) INTO v_count
      FROM playerbot_seed_spec AS s
      JOIN player.player AS p
        ON p.id = s.pid AND BINARY p.name = BINARY s.player_name AND p.job = s.job
      JOIN account.account AS a
        ON a.id = p.account_id
       AND BINARY a.login = BINARY s.login
       AND BINARY a.social_id = BINARY s.social_id
      JOIN player.player_index AS pi
        ON pi.id = a.id AND pi.pid1 = s.pid
       AND pi.pid2 = 0 AND pi.pid3 = 0 AND pi.pid4 = 0 AND pi.empire = 2
      JOIN common.playerbot_seed_state AS l
        ON l.pid = s.pid AND l.seed_version = 1
       AND l.state IN ('complete', 'adopted');
    SELECT COUNT(*) INTO v_expected FROM playerbot_seed_spec;
    IF v_count <> v_expected THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed: final row assertion failed';
    END IF;
END//
DELIMITER ;

DROP TEMPORARY TABLE IF EXISTS playerbot_seed_pending;
DROP TEMPORARY TABLE IF EXISTS playerbot_seed_missing;
DROP TEMPORARY TABLE IF EXISTS playerbot_seed_skip;
DROP TEMPORARY TABLE IF EXISTS playerbot_seed_spec;
"""
    sql = sql.replace("@@COUNT@@", str(BOT_COUNT))
    sql = sql.replace("@@FIRST@@", str(FIRST_PID))
    sql = sql.replace("@@LAST@@", str(FIRST_PID + BOT_COUNT - 1))
    return sql.replace("@@VALUES@@", ",\n".join(values))


def main(argv: list[str] | None = None) -> int:
    default_output = Path(__file__).resolve().parent.parent / "sql" / "playerbots_seed.sql"
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=default_output)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if --output is absent or differs from deterministic output",
    )
    args = parser.parse_args(argv)

    payload = render_sql(cohort()).encode("ascii")
    digest = hashlib.sha256(payload).hexdigest()
    output = args.output.resolve()

    if args.check:
        try:
            current = output.read_bytes()
        except FileNotFoundError:
            print(f"ERROR: generated snapshot is missing: {output}", file=sys.stderr)
            return 1
        if current != payload:
            actual = hashlib.sha256(current).hexdigest()
            print(
                f"ERROR: {output} is stale (actual {actual}, expected {digest})",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {output} ({BOT_COUNT} bots, sha256 {digest})")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(payload)
    print(f"wrote {output} ({BOT_COUNT} bots, sha256 {digest})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
