-- Generated by linux-port/overlays/playerbot/tools/generate_seed.py.
-- DO NOT EDIT: run the generator, then run it again with --check.
--
-- Canonical Playerbot cohort: 350 rows, explicit player PID 4..353.
-- Fresh accounts are non-login accounts: unique login/social ID, password '!'
-- and status BLOCK. Existing matching bots are adopted without changing any
-- gameplay state. Any foreign PID/name/account/index collision aborts before
-- durable changes; the Compose wrapper decides whether that is warning-only or
-- fatal according to PLAYERBOT_SEED_STRICT.

SET NAMES latin1;
USE player;

DROP TEMPORARY TABLE IF EXISTS playerbot_seed_spec;
CREATE TEMPORARY TABLE playerbot_seed_spec (
    pid         INT UNSIGNED NOT NULL,
    login       VARCHAR(30) NOT NULL,
    social_id   VARCHAR(13) NOT NULL,
    player_name VARCHAR(24) NOT NULL,
    job         TINYINT UNSIGNED NOT NULL,
    x           INT NOT NULL,
    y           INT NOT NULL,
    hp          SMALLINT NOT NULL,
    mp          SMALLINT NOT NULL,
    st          SMALLINT NOT NULL,
    ht          SMALLINT NOT NULL,
    dx          SMALLINT NOT NULL,
    iq          SMALLINT NOT NULL,
    PRIMARY KEY (pid),
    UNIQUE KEY uq_playerbot_seed_login (login),
    UNIQUE KEY uq_playerbot_seed_social (social_id),
    UNIQUE KEY uq_playerbot_seed_name (player_name)
) ENGINE=MEMORY DEFAULT CHARSET=latin1;

INSERT INTO playerbot_seed_spec
    (pid, login, social_id, player_name, job, x, y, hp, mp, st, ht, dx, iq)
VALUES
    (4, 'playerbot_001', '9000000000001', 'botdariusz', 0, 51000, 165000, 760, 260, 6, 4, 3, 3),
    (5, 'playerbot_002', '9000000000002', 'botarek', 4, 51080, 165000, 760, 260, 6, 4, 3, 3),
    (6, 'playerbot_003', '9000000000003', 'botbrutus', 1, 51160, 165000, 770, 260, 4, 3, 6, 3),
    (7, 'playerbot_004', '9000000000004', 'botcien', 5, 51240, 165000, 770, 260, 4, 3, 6, 3),
    (8, 'playerbot_005', '9000000000005', 'botluk', 2, 51320, 165000, 770, 300, 5, 3, 3, 5),
    (9, 'playerbot_006', '9000000000006', 'botmrok', 6, 51400, 165000, 770, 300, 5, 3, 3, 5),
    (10, 'playerbot_007', '9000000000007', 'botrunia', 3, 51480, 165000, 860, 320, 3, 4, 3, 6),
    (11, 'playerbot_008', '9000000000008', 'botiskra', 7, 51560, 165000, 860, 320, 3, 4, 3, 6),
    (12, 'playerbot_009', '9000000000009', 'botgrom', 0, 51640, 165000, 760, 260, 6, 4, 3, 3),
    (13, 'playerbot_010', '9000000000010', 'botprobe', 4, 51720, 165000, 760, 260, 6, 4, 3, 3),
    (14, 'playerbot_011', '9000000000011', 'botvalkyrie', 1, 51800, 165000, 770, 260, 4, 3, 6, 3),
    (15, 'playerbot_012', '9000000000012', 'botshadow', 5, 51880, 165000, 770, 260, 4, 3, 6, 3),
    (16, 'playerbot_013', '9000000000013', 'botviper', 2, 51960, 165000, 770, 300, 5, 3, 3, 5),
    (17, 'playerbot_014', '9000000000014', 'botphantom', 6, 52040, 165000, 770, 300, 5, 3, 3, 5),
    (18, 'playerbot_015', '9000000000015', 'botwitch', 3, 52120, 165000, 860, 320, 3, 4, 3, 6),
    (19, 'playerbot_016', '9000000000016', 'botblaze', 7, 52200, 165000, 860, 320, 3, 4, 3, 6),
    (20, 'playerbot_017', '9000000000017', 'botstorm', 0, 52280, 165000, 760, 260, 6, 4, 3, 3),
    (21, 'playerbot_018', '9000000000018', 'bottitan', 4, 52360, 165000, 760, 260, 6, 4, 3, 3),
    (22, 'playerbot_019', '9000000000019', 'botglory', 1, 52440, 165000, 770, 260, 4, 3, 6, 3),
    (23, 'playerbot_020', '9000000000020', 'botghost', 5, 52520, 165000, 770, 260, 4, 3, 6, 3),
    (24, 'playerbot_021', '9000000000021', 'botraven', 2, 52600, 165000, 770, 300, 5, 3, 3, 5),
    (25, 'playerbot_022', '9000000000022', 'botabyss', 6, 52680, 165000, 770, 300, 5, 3, 3, 5),
    (26, 'playerbot_023', '9000000000023', 'botmystic', 3, 52760, 165000, 860, 320, 3, 4, 3, 6),
    (27, 'playerbot_024', '9000000000024', 'botoracle', 7, 52840, 165000, 860, 320, 3, 4, 3, 6),
    (28, 'playerbot_025', '9000000000025', 'botsun', 0, 52920, 165000, 760, 260, 6, 4, 3, 3),
    (29, 'playerbot_026', '9000000000026', 'botknight', 4, 51000, 165120, 760, 260, 6, 4, 3, 3),
    (30, 'playerbot_027', '9000000000027', 'botblade', 1, 51080, 165120, 770, 260, 4, 3, 6, 3),
    (31, 'playerbot_028', '9000000000028', 'botdusk', 5, 51160, 165120, 770, 260, 4, 3, 6, 3),
    (32, 'playerbot_029', '9000000000029', 'botsilent', 2, 51240, 165120, 770, 300, 5, 3, 3, 5),
    (33, 'playerbot_030', '9000000000030', 'botchaos', 6, 51320, 165120, 770, 300, 5, 3, 3, 5),
    (34, 'playerbot_031', '9000000000031', 'botvoid', 3, 51400, 165120, 860, 320, 3, 4, 3, 6),
    (35, 'playerbot_032', '9000000000032', 'botnova', 7, 51480, 165120, 860, 320, 3, 4, 3, 6),
    (36, 'playerbot_033', '9000000000033', 'botfrost', 0, 51560, 165120, 760, 260, 6, 4, 3, 3),
    (37, 'playerbot_034', '9000000000034', 'botinferno', 4, 51640, 165120, 760, 260, 6, 4, 3, 3),
    (38, 'playerbot_035', '9000000000035', 'botecho', 1, 51720, 165120, 770, 260, 4, 3, 6, 3),
    (39, 'playerbot_036', '9000000000036', 'botspecter', 5, 51800, 165120, 770, 260, 4, 3, 6, 3),
    (40, 'playerbot_037', '9000000000037', 'botdraco', 2, 51880, 165120, 770, 300, 5, 3, 3, 5),
    (41, 'playerbot_038', '9000000000038', 'botsaber', 6, 51960, 165120, 770, 300, 5, 3, 3, 5),
    (42, 'playerbot_039', '9000000000039', 'botfury', 3, 52040, 165120, 860, 320, 3, 4, 3, 6),
    (43, 'playerbot_040', '9000000000040', 'botzenith', 7, 52120, 165120, 860, 320, 3, 4, 3, 6),
    (44, 'playerbot_041', '9000000000041', 'botonyx', 0, 52200, 165120, 760, 260, 6, 4, 3, 3),
    (45, 'playerbot_042', '9000000000042', 'botscarlet', 4, 52280, 165120, 760, 260, 6, 4, 3, 3),
    (46, 'playerbot_043', '9000000000043', 'botsilver', 1, 52360, 165120, 770, 260, 4, 3, 6, 3),
    (47, 'playerbot_044', '9000000000044', 'botamber', 5, 52440, 165120, 770, 260, 4, 3, 6, 3),
    (48, 'playerbot_045', '9000000000045', 'botjade', 2, 52520, 165120, 770, 300, 5, 3, 3, 5),
    (49, 'playerbot_046', '9000000000046', 'botcoral', 6, 52600, 165120, 770, 300, 5, 3, 3, 5),
    (50, 'playerbot_047', '9000000000047', 'botflint', 3, 52680, 165120, 860, 320, 3, 4, 3, 6),
    (51, 'playerbot_048', '9000000000048', 'botiron', 7, 52760, 165120, 860, 320, 3, 4, 3, 6),
    (52, 'playerbot_049', '9000000000049', 'botsteel', 0, 52840, 165120, 760, 260, 6, 4, 3, 3),
    (53, 'playerbot_050', '9000000000050', 'bottalon', 4, 52920, 165120, 760, 260, 6, 4, 3, 3),
    (54, 'playerbot_051', '9000000000051', 'botfang', 1, 51000, 165240, 770, 260, 4, 3, 6, 3),
    (55, 'playerbot_052', '9000000000052', 'botclaw', 5, 51080, 165240, 770, 260, 4, 3, 6, 3),
    (56, 'playerbot_053', '9000000000053', 'bothawk', 2, 51160, 165240, 770, 300, 5, 3, 3, 5),
    (57, 'playerbot_054', '9000000000054', 'botfalcon', 6, 51240, 165240, 770, 300, 5, 3, 3, 5),
    (58, 'playerbot_055', '9000000000055', 'boteagle', 3, 51320, 165240, 860, 320, 3, 4, 3, 6),
    (59, 'playerbot_056', '9000000000056', 'botwolf', 7, 51400, 165240, 860, 320, 3, 4, 3, 6),
    (60, 'playerbot_057', '9000000000057', 'botlynx', 0, 51480, 165240, 760, 260, 6, 4, 3, 3),
    (61, 'playerbot_058', '9000000000058', 'botpanther', 4, 51560, 165240, 760, 260, 6, 4, 3, 3),
    (62, 'playerbot_059', '9000000000059', 'bottiger', 1, 51640, 165240, 770, 260, 4, 3, 6, 3),
    (63, 'playerbot_060', '9000000000060', 'botbear', 5, 51720, 165240, 770, 260, 4, 3, 6, 3),
    (64, 'playerbot_061', '9000000000061', 'botlion', 2, 51800, 165240, 770, 300, 5, 3, 3, 5),
    (65, 'playerbot_062', '9000000000062', 'botcobra', 6, 51880, 165240, 770, 300, 5, 3, 3, 5),
    (66, 'playerbot_063', '9000000000063', 'bothydra', 3, 51960, 165240, 860, 320, 3, 4, 3, 6),
    (67, 'playerbot_064', '9000000000064', 'botchimera', 7, 52040, 165240, 860, 320, 3, 4, 3, 6),
    (68, 'playerbot_065', '9000000000065', 'botdariusz2', 0, 52120, 165240, 760, 260, 6, 4, 3, 3),
    (69, 'playerbot_066', '9000000000066', 'botarek2', 4, 52200, 165240, 760, 260, 6, 4, 3, 3),
    (70, 'playerbot_067', '9000000000067', 'botbrutus2', 1, 52280, 165240, 770, 260, 4, 3, 6, 3),
    (71, 'playerbot_068', '9000000000068', 'botcien2', 5, 52360, 165240, 770, 260, 4, 3, 6, 3),
    (72, 'playerbot_069', '9000000000069', 'botluk2', 2, 52440, 165240, 770, 300, 5, 3, 3, 5),
    (73, 'playerbot_070', '9000000000070', 'botmrok2', 6, 52520, 165240, 770, 300, 5, 3, 3, 5),
    (74, 'playerbot_071', '9000000000071', 'botrunia2', 3, 52600, 165240, 860, 320, 3, 4, 3, 6),
    (75, 'playerbot_072', '9000000000072', 'botiskra2', 7, 52680, 165240, 860, 320, 3, 4, 3, 6),
    (76, 'playerbot_073', '9000000000073', 'botgrom2', 0, 52760, 165240, 760, 260, 6, 4, 3, 3),
    (77, 'playerbot_074', '9000000000074', 'botprobe2', 4, 52840, 165240, 760, 260, 6, 4, 3, 3),
    (78, 'playerbot_075', '9000000000075', 'botvalkyrie2', 1, 52920, 165240, 770, 260, 4, 3, 6, 3),
    (79, 'playerbot_076', '9000000000076', 'botshadow2', 5, 51000, 165360, 770, 260, 4, 3, 6, 3),
    (80, 'playerbot_077', '9000000000077', 'botviper2', 2, 51080, 165360, 770, 300, 5, 3, 3, 5),
    (81, 'playerbot_078', '9000000000078', 'botphantom2', 6, 51160, 165360, 770, 300, 5, 3, 3, 5),
    (82, 'playerbot_079', '9000000000079', 'botwitch2', 3, 51240, 165360, 860, 320, 3, 4, 3, 6),
    (83, 'playerbot_080', '9000000000080', 'botblaze2', 7, 51320, 165360, 860, 320, 3, 4, 3, 6),
    (84, 'playerbot_081', '9000000000081', 'botstorm2', 0, 51400, 165360, 760, 260, 6, 4, 3, 3),
    (85, 'playerbot_082', '9000000000082', 'bottitan2', 4, 51480, 165360, 760, 260, 6, 4, 3, 3),
    (86, 'playerbot_083', '9000000000083', 'botglory2', 1, 51560, 165360, 770, 260, 4, 3, 6, 3),
    (87, 'playerbot_084', '9000000000084', 'botghost2', 5, 51640, 165360, 770, 260, 4, 3, 6, 3),
    (88, 'playerbot_085', '9000000000085', 'botraven2', 2, 51720, 165360, 770, 300, 5, 3, 3, 5),
    (89, 'playerbot_086', '9000000000086', 'botabyss2', 6, 51800, 165360, 770, 300, 5, 3, 3, 5),
    (90, 'playerbot_087', '9000000000087', 'botmystic2', 3, 51880, 165360, 860, 320, 3, 4, 3, 6),
    (91, 'playerbot_088', '9000000000088', 'botoracle2', 7, 51960, 165360, 860, 320, 3, 4, 3, 6),
    (92, 'playerbot_089', '9000000000089', 'botsun2', 0, 52040, 165360, 760, 260, 6, 4, 3, 3),
    (93, 'playerbot_090', '9000000000090', 'botknight2', 4, 52120, 165360, 760, 260, 6, 4, 3, 3),
    (94, 'playerbot_091', '9000000000091', 'botblade2', 1, 52200, 165360, 770, 260, 4, 3, 6, 3),
    (95, 'playerbot_092', '9000000000092', 'botdusk2', 5, 52280, 165360, 770, 260, 4, 3, 6, 3),
    (96, 'playerbot_093', '9000000000093', 'botsilent2', 2, 52360, 165360, 770, 300, 5, 3, 3, 5),
    (97, 'playerbot_094', '9000000000094', 'botchaos2', 6, 52440, 165360, 770, 300, 5, 3, 3, 5),
    (98, 'playerbot_095', '9000000000095', 'botvoid2', 3, 52520, 165360, 860, 320, 3, 4, 3, 6),
    (99, 'playerbot_096', '9000000000096', 'botnova2', 7, 52600, 165360, 860, 320, 3, 4, 3, 6),
    (100, 'playerbot_097', '9000000000097', 'botfrost2', 0, 52680, 165360, 760, 260, 6, 4, 3, 3),
    (101, 'playerbot_098', '9000000000098', 'botinferno2', 4, 52760, 165360, 760, 260, 6, 4, 3, 3),
    (102, 'playerbot_099', '9000000000099', 'botecho2', 1, 52840, 165360, 770, 260, 4, 3, 6, 3),
    (103, 'playerbot_100', '9000000000100', 'botspecter2', 5, 52920, 165360, 770, 260, 4, 3, 6, 3),
    (104, 'playerbot_101', '9000000000101', 'botdraco2', 2, 51000, 165480, 770, 300, 5, 3, 3, 5),
    (105, 'playerbot_102', '9000000000102', 'botsaber2', 6, 51080, 165480, 770, 300, 5, 3, 3, 5),
    (106, 'playerbot_103', '9000000000103', 'botfury2', 3, 51160, 165480, 860, 320, 3, 4, 3, 6),
    (107, 'playerbot_104', '9000000000104', 'botzenith2', 7, 51240, 165480, 860, 320, 3, 4, 3, 6),
    (108, 'playerbot_105', '9000000000105', 'botonyx2', 0, 51320, 165480, 760, 260, 6, 4, 3, 3),
    (109, 'playerbot_106', '9000000000106', 'botscarlet2', 4, 51400, 165480, 760, 260, 6, 4, 3, 3),
    (110, 'playerbot_107', '9000000000107', 'botsilver2', 1, 51480, 165480, 770, 260, 4, 3, 6, 3),
    (111, 'playerbot_108', '9000000000108', 'botamber2', 5, 51560, 165480, 770, 260, 4, 3, 6, 3),
    (112, 'playerbot_109', '9000000000109', 'botjade2', 2, 51640, 165480, 770, 300, 5, 3, 3, 5),
    (113, 'playerbot_110', '9000000000110', 'botcoral2', 6, 51720, 165480, 770, 300, 5, 3, 3, 5),
    (114, 'playerbot_111', '9000000000111', 'botflint2', 3, 51800, 165480, 860, 320, 3, 4, 3, 6),
    (115, 'playerbot_112', '9000000000112', 'botiron2', 7, 51880, 165480, 860, 320, 3, 4, 3, 6),
    (116, 'playerbot_113', '9000000000113', 'botsteel2', 0, 51960, 165480, 760, 260, 6, 4, 3, 3),
    (117, 'playerbot_114', '9000000000114', 'bottalon2', 4, 52040, 165480, 760, 260, 6, 4, 3, 3),
    (118, 'playerbot_115', '9000000000115', 'botfang2', 1, 52120, 165480, 770, 260, 4, 3, 6, 3),
    (119, 'playerbot_116', '9000000000116', 'botclaw2', 5, 52200, 165480, 770, 260, 4, 3, 6, 3),
    (120, 'playerbot_117', '9000000000117', 'bothawk2', 2, 52280, 165480, 770, 300, 5, 3, 3, 5),
    (121, 'playerbot_118', '9000000000118', 'botfalcon2', 6, 52360, 165480, 770, 300, 5, 3, 3, 5),
    (122, 'playerbot_119', '9000000000119', 'boteagle2', 3, 52440, 165480, 860, 320, 3, 4, 3, 6),
    (123, 'playerbot_120', '9000000000120', 'botwolf2', 7, 52520, 165480, 860, 320, 3, 4, 3, 6),
    (124, 'playerbot_121', '9000000000121', 'botlynx2', 0, 52600, 165480, 760, 260, 6, 4, 3, 3),
    (125, 'playerbot_122', '9000000000122', 'botpanther2', 4, 52680, 165480, 760, 260, 6, 4, 3, 3),
    (126, 'playerbot_123', '9000000000123', 'bottiger2', 1, 52760, 165480, 770, 260, 4, 3, 6, 3),
    (127, 'playerbot_124', '9000000000124', 'botbear2', 5, 52840, 165480, 770, 260, 4, 3, 6, 3),
    (128, 'playerbot_125', '9000000000125', 'botlion2', 2, 52920, 165480, 770, 300, 5, 3, 3, 5),
    (129, 'playerbot_126', '9000000000126', 'botcobra2', 6, 51000, 165600, 770, 300, 5, 3, 3, 5),
    (130, 'playerbot_127', '9000000000127', 'bothydra2', 3, 51080, 165600, 860, 320, 3, 4, 3, 6),
    (131, 'playerbot_128', '9000000000128', 'botchimera2', 7, 51160, 165600, 860, 320, 3, 4, 3, 6),
    (132, 'playerbot_129', '9000000000129', 'botdariusz3', 0, 51240, 165600, 760, 260, 6, 4, 3, 3),
    (133, 'playerbot_130', '9000000000130', 'botarek3', 4, 51320, 165600, 760, 260, 6, 4, 3, 3),
    (134, 'playerbot_131', '9000000000131', 'botbrutus3', 1, 51400, 165600, 770, 260, 4, 3, 6, 3),
    (135, 'playerbot_132', '9000000000132', 'botcien3', 5, 51480, 165600, 770, 260, 4, 3, 6, 3),
    (136, 'playerbot_133', '9000000000133', 'botluk3', 2, 51560, 165600, 770, 300, 5, 3, 3, 5),
    (137, 'playerbot_134', '9000000000134', 'botmrok3', 6, 51640, 165600, 770, 300, 5, 3, 3, 5),
    (138, 'playerbot_135', '9000000000135', 'botrunia3', 3, 51720, 165600, 860, 320, 3, 4, 3, 6),
    (139, 'playerbot_136', '9000000000136', 'botiskra3', 7, 51800, 165600, 860, 320, 3, 4, 3, 6),
    (140, 'playerbot_137', '9000000000137', 'botgrom3', 0, 51880, 165600, 760, 260, 6, 4, 3, 3),
    (141, 'playerbot_138', '9000000000138', 'botprobe3', 4, 51960, 165600, 760, 260, 6, 4, 3, 3),
    (142, 'playerbot_139', '9000000000139', 'botvalkyrie3', 1, 52040, 165600, 770, 260, 4, 3, 6, 3),
    (143, 'playerbot_140', '9000000000140', 'botshadow3', 5, 52120, 165600, 770, 260, 4, 3, 6, 3),
    (144, 'playerbot_141', '9000000000141', 'botviper3', 2, 52200, 165600, 770, 300, 5, 3, 3, 5),
    (145, 'playerbot_142', '9000000000142', 'botphantom3', 6, 52280, 165600, 770, 300, 5, 3, 3, 5),
    (146, 'playerbot_143', '9000000000143', 'botwitch3', 3, 52360, 165600, 860, 320, 3, 4, 3, 6),
    (147, 'playerbot_144', '9000000000144', 'botblaze3', 7, 52440, 165600, 860, 320, 3, 4, 3, 6),
    (148, 'playerbot_145', '9000000000145', 'botstorm3', 0, 52520, 165600, 760, 260, 6, 4, 3, 3),
    (149, 'playerbot_146', '9000000000146', 'bottitan3', 4, 52600, 165600, 760, 260, 6, 4, 3, 3),
    (150, 'playerbot_147', '9000000000147', 'botglory3', 1, 52680, 165600, 770, 260, 4, 3, 6, 3),
    (151, 'playerbot_148', '9000000000148', 'botghost3', 5, 52760, 165600, 770, 260, 4, 3, 6, 3),
    (152, 'playerbot_149', '9000000000149', 'botraven3', 2, 52840, 165600, 770, 300, 5, 3, 3, 5),
    (153, 'playerbot_150', '9000000000150', 'botabyss3', 6, 52920, 165600, 770, 300, 5, 3, 3, 5),
    (154, 'playerbot_151', '9000000000151', 'botmystic3', 3, 51000, 165720, 860, 320, 3, 4, 3, 6),
    (155, 'playerbot_152', '9000000000152', 'botoracle3', 7, 51080, 165720, 860, 320, 3, 4, 3, 6),
    (156, 'playerbot_153', '9000000000153', 'botsun3', 0, 51160, 165720, 760, 260, 6, 4, 3, 3),
    (157, 'playerbot_154', '9000000000154', 'botknight3', 4, 51240, 165720, 760, 260, 6, 4, 3, 3),
    (158, 'playerbot_155', '9000000000155', 'botblade3', 1, 51320, 165720, 770, 260, 4, 3, 6, 3),
    (159, 'playerbot_156', '9000000000156', 'botdusk3', 5, 51400, 165720, 770, 260, 4, 3, 6, 3),
    (160, 'playerbot_157', '9000000000157', 'botsilent3', 2, 51480, 165720, 770, 300, 5, 3, 3, 5),
    (161, 'playerbot_158', '9000000000158', 'botchaos3', 6, 51560, 165720, 770, 300, 5, 3, 3, 5),
    (162, 'playerbot_159', '9000000000159', 'botvoid3', 3, 51640, 165720, 860, 320, 3, 4, 3, 6),
    (163, 'playerbot_160', '9000000000160', 'botnova3', 7, 51720, 165720, 860, 320, 3, 4, 3, 6),
    (164, 'playerbot_161', '9000000000161', 'botfrost3', 0, 51800, 165720, 760, 260, 6, 4, 3, 3),
    (165, 'playerbot_162', '9000000000162', 'botinferno3', 4, 51880, 165720, 760, 260, 6, 4, 3, 3),
    (166, 'playerbot_163', '9000000000163', 'botecho3', 1, 51960, 165720, 770, 260, 4, 3, 6, 3),
    (167, 'playerbot_164', '9000000000164', 'botspecter3', 5, 52040, 165720, 770, 260, 4, 3, 6, 3),
    (168, 'playerbot_165', '9000000000165', 'botdraco3', 2, 52120, 165720, 770, 300, 5, 3, 3, 5),
    (169, 'playerbot_166', '9000000000166', 'botsaber3', 6, 52200, 165720, 770, 300, 5, 3, 3, 5),
    (170, 'playerbot_167', '9000000000167', 'botfury3', 3, 52280, 165720, 860, 320, 3, 4, 3, 6),
    (171, 'playerbot_168', '9000000000168', 'botzenith3', 7, 52360, 165720, 860, 320, 3, 4, 3, 6),
    (172, 'playerbot_169', '9000000000169', 'botonyx3', 0, 52440, 165720, 760, 260, 6, 4, 3, 3),
    (173, 'playerbot_170', '9000000000170', 'botscarlet3', 4, 52520, 165720, 760, 260, 6, 4, 3, 3),
    (174, 'playerbot_171', '9000000000171', 'botsilver3', 1, 52600, 165720, 770, 260, 4, 3, 6, 3),
    (175, 'playerbot_172', '9000000000172', 'botamber3', 5, 52680, 165720, 770, 260, 4, 3, 6, 3),
    (176, 'playerbot_173', '9000000000173', 'botjade3', 2, 52760, 165720, 770, 300, 5, 3, 3, 5),
    (177, 'playerbot_174', '9000000000174', 'botcoral3', 6, 52840, 165720, 770, 300, 5, 3, 3, 5),
    (178, 'playerbot_175', '9000000000175', 'botflint3', 3, 52920, 165720, 860, 320, 3, 4, 3, 6),
    (179, 'playerbot_176', '9000000000176', 'botiron3', 7, 51000, 165840, 860, 320, 3, 4, 3, 6),
    (180, 'playerbot_177', '9000000000177', 'botsteel3', 0, 51080, 165840, 760, 260, 6, 4, 3, 3),
    (181, 'playerbot_178', '9000000000178', 'bottalon3', 4, 51160, 165840, 760, 260, 6, 4, 3, 3),
    (182, 'playerbot_179', '9000000000179', 'botfang3', 1, 51240, 165840, 770, 260, 4, 3, 6, 3),
    (183, 'playerbot_180', '9000000000180', 'botclaw3', 5, 51320, 165840, 770, 260, 4, 3, 6, 3),
    (184, 'playerbot_181', '9000000000181', 'bothawk3', 2, 51400, 165840, 770, 300, 5, 3, 3, 5),
    (185, 'playerbot_182', '9000000000182', 'botfalcon3', 6, 51480, 165840, 770, 300, 5, 3, 3, 5),
    (186, 'playerbot_183', '9000000000183', 'boteagle3', 3, 51560, 165840, 860, 320, 3, 4, 3, 6),
    (187, 'playerbot_184', '9000000000184', 'botwolf3', 7, 51640, 165840, 860, 320, 3, 4, 3, 6),
    (188, 'playerbot_185', '9000000000185', 'botlynx3', 0, 51720, 165840, 760, 260, 6, 4, 3, 3),
    (189, 'playerbot_186', '9000000000186', 'botpanther3', 4, 51800, 165840, 760, 260, 6, 4, 3, 3),
    (190, 'playerbot_187', '9000000000187', 'bottiger3', 1, 51880, 165840, 770, 260, 4, 3, 6, 3),
    (191, 'playerbot_188', '9000000000188', 'botbear3', 5, 51960, 165840, 770, 260, 4, 3, 6, 3),
    (192, 'playerbot_189', '9000000000189', 'botlion3', 2, 52040, 165840, 770, 300, 5, 3, 3, 5),
    (193, 'playerbot_190', '9000000000190', 'botcobra3', 6, 52120, 165840, 770, 300, 5, 3, 3, 5),
    (194, 'playerbot_191', '9000000000191', 'bothydra3', 3, 52200, 165840, 860, 320, 3, 4, 3, 6),
    (195, 'playerbot_192', '9000000000192', 'botchimera3', 7, 52280, 165840, 860, 320, 3, 4, 3, 6),
    (196, 'playerbot_193', '9000000000193', 'botdariusz4', 0, 52360, 165840, 760, 260, 6, 4, 3, 3),
    (197, 'playerbot_194', '9000000000194', 'botarek4', 4, 52440, 165840, 760, 260, 6, 4, 3, 3),
    (198, 'playerbot_195', '9000000000195', 'botbrutus4', 1, 52520, 165840, 770, 260, 4, 3, 6, 3),
    (199, 'playerbot_196', '9000000000196', 'botcien4', 5, 52600, 165840, 770, 260, 4, 3, 6, 3),
    (200, 'playerbot_197', '9000000000197', 'botluk4', 2, 52680, 165840, 770, 300, 5, 3, 3, 5),
    (201, 'playerbot_198', '9000000000198', 'botmrok4', 6, 52760, 165840, 770, 300, 5, 3, 3, 5),
    (202, 'playerbot_199', '9000000000199', 'botrunia4', 3, 52840, 165840, 860, 320, 3, 4, 3, 6),
    (203, 'playerbot_200', '9000000000200', 'botiskra4', 7, 52920, 165840, 860, 320, 3, 4, 3, 6),
    (204, 'playerbot_201', '9000000000201', 'botgrom4', 0, 51000, 165960, 760, 260, 6, 4, 3, 3),
    (205, 'playerbot_202', '9000000000202', 'botprobe4', 4, 51080, 165960, 760, 260, 6, 4, 3, 3),
    (206, 'playerbot_203', '9000000000203', 'botvalkyrie4', 1, 51160, 165960, 770, 260, 4, 3, 6, 3),
    (207, 'playerbot_204', '9000000000204', 'botshadow4', 5, 51240, 165960, 770, 260, 4, 3, 6, 3),
    (208, 'playerbot_205', '9000000000205', 'botviper4', 2, 51320, 165960, 770, 300, 5, 3, 3, 5),
    (209, 'playerbot_206', '9000000000206', 'botphantom4', 6, 51400, 165960, 770, 300, 5, 3, 3, 5),
    (210, 'playerbot_207', '9000000000207', 'botwitch4', 3, 51480, 165960, 860, 320, 3, 4, 3, 6),
    (211, 'playerbot_208', '9000000000208', 'botblaze4', 7, 51560, 165960, 860, 320, 3, 4, 3, 6),
    (212, 'playerbot_209', '9000000000209', 'botstorm4', 0, 51640, 165960, 760, 260, 6, 4, 3, 3),
    (213, 'playerbot_210', '9000000000210', 'bottitan4', 4, 51720, 165960, 760, 260, 6, 4, 3, 3),
    (214, 'playerbot_211', '9000000000211', 'botglory4', 1, 51800, 165960, 770, 260, 4, 3, 6, 3),
    (215, 'playerbot_212', '9000000000212', 'botghost4', 5, 51880, 165960, 770, 260, 4, 3, 6, 3),
    (216, 'playerbot_213', '9000000000213', 'botraven4', 2, 51960, 165960, 770, 300, 5, 3, 3, 5),
    (217, 'playerbot_214', '9000000000214', 'botabyss4', 6, 52040, 165960, 770, 300, 5, 3, 3, 5),
    (218, 'playerbot_215', '9000000000215', 'botmystic4', 3, 52120, 165960, 860, 320, 3, 4, 3, 6),
    (219, 'playerbot_216', '9000000000216', 'botoracle4', 7, 52200, 165960, 860, 320, 3, 4, 3, 6),
    (220, 'playerbot_217', '9000000000217', 'botsun4', 0, 52280, 165960, 760, 260, 6, 4, 3, 3),
    (221, 'playerbot_218', '9000000000218', 'botknight4', 4, 52360, 165960, 760, 260, 6, 4, 3, 3),
    (222, 'playerbot_219', '9000000000219', 'botblade4', 1, 52440, 165960, 770, 260, 4, 3, 6, 3),
    (223, 'playerbot_220', '9000000000220', 'botdusk4', 5, 52520, 165960, 770, 260, 4, 3, 6, 3),
    (224, 'playerbot_221', '9000000000221', 'botsilent4', 2, 52600, 165960, 770, 300, 5, 3, 3, 5),
    (225, 'playerbot_222', '9000000000222', 'botchaos4', 6, 52680, 165960, 770, 300, 5, 3, 3, 5),
    (226, 'playerbot_223', '9000000000223', 'botvoid4', 3, 52760, 165960, 860, 320, 3, 4, 3, 6),
    (227, 'playerbot_224', '9000000000224', 'botnova4', 7, 52840, 165960, 860, 320, 3, 4, 3, 6),
    (228, 'playerbot_225', '9000000000225', 'botfrost4', 0, 52920, 165960, 760, 260, 6, 4, 3, 3),
    (229, 'playerbot_226', '9000000000226', 'botinferno4', 4, 51000, 166080, 760, 260, 6, 4, 3, 3),
    (230, 'playerbot_227', '9000000000227', 'botecho4', 1, 51080, 166080, 770, 260, 4, 3, 6, 3),
    (231, 'playerbot_228', '9000000000228', 'botspecter4', 5, 51160, 166080, 770, 260, 4, 3, 6, 3),
    (232, 'playerbot_229', '9000000000229', 'botdraco4', 2, 51240, 166080, 770, 300, 5, 3, 3, 5),
    (233, 'playerbot_230', '9000000000230', 'botsaber4', 6, 51320, 166080, 770, 300, 5, 3, 3, 5),
    (234, 'playerbot_231', '9000000000231', 'botfury4', 3, 51400, 166080, 860, 320, 3, 4, 3, 6),
    (235, 'playerbot_232', '9000000000232', 'botzenith4', 7, 51480, 166080, 860, 320, 3, 4, 3, 6),
    (236, 'playerbot_233', '9000000000233', 'botonyx4', 0, 51560, 166080, 760, 260, 6, 4, 3, 3),
    (237, 'playerbot_234', '9000000000234', 'botscarlet4', 4, 51640, 166080, 760, 260, 6, 4, 3, 3),
    (238, 'playerbot_235', '9000000000235', 'botsilver4', 1, 51720, 166080, 770, 260, 4, 3, 6, 3),
    (239, 'playerbot_236', '9000000000236', 'botamber4', 5, 51800, 166080, 770, 260, 4, 3, 6, 3),
    (240, 'playerbot_237', '9000000000237', 'botjade4', 2, 51880, 166080, 770, 300, 5, 3, 3, 5),
    (241, 'playerbot_238', '9000000000238', 'botcoral4', 6, 51960, 166080, 770, 300, 5, 3, 3, 5),
    (242, 'playerbot_239', '9000000000239', 'botflint4', 3, 52040, 166080, 860, 320, 3, 4, 3, 6),
    (243, 'playerbot_240', '9000000000240', 'botiron4', 7, 52120, 166080, 860, 320, 3, 4, 3, 6),
    (244, 'playerbot_241', '9000000000241', 'botsteel4', 0, 52200, 166080, 760, 260, 6, 4, 3, 3),
    (245, 'playerbot_242', '9000000000242', 'bottalon4', 4, 52280, 166080, 760, 260, 6, 4, 3, 3),
    (246, 'playerbot_243', '9000000000243', 'botfang4', 1, 52360, 166080, 770, 260, 4, 3, 6, 3),
    (247, 'playerbot_244', '9000000000244', 'botclaw4', 5, 52440, 166080, 770, 260, 4, 3, 6, 3),
    (248, 'playerbot_245', '9000000000245', 'bothawk4', 2, 52520, 166080, 770, 300, 5, 3, 3, 5),
    (249, 'playerbot_246', '9000000000246', 'botfalcon4', 6, 52600, 166080, 770, 300, 5, 3, 3, 5),
    (250, 'playerbot_247', '9000000000247', 'boteagle4', 3, 52680, 166080, 860, 320, 3, 4, 3, 6),
    (251, 'playerbot_248', '9000000000248', 'botwolf4', 7, 52760, 166080, 860, 320, 3, 4, 3, 6),
    (252, 'playerbot_249', '9000000000249', 'botlynx4', 0, 52840, 166080, 760, 260, 6, 4, 3, 3),
    (253, 'playerbot_250', '9000000000250', 'botpanther4', 4, 52920, 166080, 760, 260, 6, 4, 3, 3),
    (254, 'playerbot_251', '9000000000251', 'bottiger4', 1, 51000, 166200, 770, 260, 4, 3, 6, 3),
    (255, 'playerbot_252', '9000000000252', 'botbear4', 5, 51080, 166200, 770, 260, 4, 3, 6, 3),
    (256, 'playerbot_253', '9000000000253', 'botlion4', 2, 51160, 166200, 770, 300, 5, 3, 3, 5),
    (257, 'playerbot_254', '9000000000254', 'botcobra4', 6, 51240, 166200, 770, 300, 5, 3, 3, 5),
    (258, 'playerbot_255', '9000000000255', 'bothydra4', 3, 51320, 166200, 860, 320, 3, 4, 3, 6),
    (259, 'playerbot_256', '9000000000256', 'botchimera4', 7, 51400, 166200, 860, 320, 3, 4, 3, 6),
    (260, 'playerbot_257', '9000000000257', 'botdariusz5', 0, 51480, 166200, 760, 260, 6, 4, 3, 3),
    (261, 'playerbot_258', '9000000000258', 'botarek5', 4, 51560, 166200, 760, 260, 6, 4, 3, 3),
    (262, 'playerbot_259', '9000000000259', 'botbrutus5', 1, 51640, 166200, 770, 260, 4, 3, 6, 3),
    (263, 'playerbot_260', '9000000000260', 'botcien5', 5, 51720, 166200, 770, 260, 4, 3, 6, 3),
    (264, 'playerbot_261', '9000000000261', 'botluk5', 2, 51800, 166200, 770, 300, 5, 3, 3, 5),
    (265, 'playerbot_262', '9000000000262', 'botmrok5', 6, 51880, 166200, 770, 300, 5, 3, 3, 5),
    (266, 'playerbot_263', '9000000000263', 'botrunia5', 3, 51960, 166200, 860, 320, 3, 4, 3, 6),
    (267, 'playerbot_264', '9000000000264', 'botiskra5', 7, 52040, 166200, 860, 320, 3, 4, 3, 6),
    (268, 'playerbot_265', '9000000000265', 'botgrom5', 0, 52120, 166200, 760, 260, 6, 4, 3, 3),
    (269, 'playerbot_266', '9000000000266', 'botprobe5', 4, 52200, 166200, 760, 260, 6, 4, 3, 3),
    (270, 'playerbot_267', '9000000000267', 'botvalkyrie5', 1, 52280, 166200, 770, 260, 4, 3, 6, 3),
    (271, 'playerbot_268', '9000000000268', 'botshadow5', 5, 52360, 166200, 770, 260, 4, 3, 6, 3),
    (272, 'playerbot_269', '9000000000269', 'botviper5', 2, 52440, 166200, 770, 300, 5, 3, 3, 5),
    (273, 'playerbot_270', '9000000000270', 'botphantom5', 6, 52520, 166200, 770, 300, 5, 3, 3, 5),
    (274, 'playerbot_271', '9000000000271', 'botwitch5', 3, 52600, 166200, 860, 320, 3, 4, 3, 6),
    (275, 'playerbot_272', '9000000000272', 'botblaze5', 7, 52680, 166200, 860, 320, 3, 4, 3, 6),
    (276, 'playerbot_273', '9000000000273', 'botstorm5', 0, 52760, 166200, 760, 260, 6, 4, 3, 3),
    (277, 'playerbot_274', '9000000000274', 'bottitan5', 4, 52840, 166200, 760, 260, 6, 4, 3, 3),
    (278, 'playerbot_275', '9000000000275', 'botglory5', 1, 52920, 166200, 770, 260, 4, 3, 6, 3),
    (279, 'playerbot_276', '9000000000276', 'botghost5', 5, 51000, 166320, 770, 260, 4, 3, 6, 3),
    (280, 'playerbot_277', '9000000000277', 'botraven5', 2, 51080, 166320, 770, 300, 5, 3, 3, 5),
    (281, 'playerbot_278', '9000000000278', 'botabyss5', 6, 51160, 166320, 770, 300, 5, 3, 3, 5),
    (282, 'playerbot_279', '9000000000279', 'botmystic5', 3, 51240, 166320, 860, 320, 3, 4, 3, 6),
    (283, 'playerbot_280', '9000000000280', 'botoracle5', 7, 51320, 166320, 860, 320, 3, 4, 3, 6),
    (284, 'playerbot_281', '9000000000281', 'botsun5', 0, 51400, 166320, 760, 260, 6, 4, 3, 3),
    (285, 'playerbot_282', '9000000000282', 'botknight5', 4, 51480, 166320, 760, 260, 6, 4, 3, 3),
    (286, 'playerbot_283', '9000000000283', 'botblade5', 1, 51560, 166320, 770, 260, 4, 3, 6, 3),
    (287, 'playerbot_284', '9000000000284', 'botdusk5', 5, 51640, 166320, 770, 260, 4, 3, 6, 3),
    (288, 'playerbot_285', '9000000000285', 'botsilent5', 2, 51720, 166320, 770, 300, 5, 3, 3, 5),
    (289, 'playerbot_286', '9000000000286', 'botchaos5', 6, 51800, 166320, 770, 300, 5, 3, 3, 5),
    (290, 'playerbot_287', '9000000000287', 'botvoid5', 3, 51880, 166320, 860, 320, 3, 4, 3, 6),
    (291, 'playerbot_288', '9000000000288', 'botnova5', 7, 51960, 166320, 860, 320, 3, 4, 3, 6),
    (292, 'playerbot_289', '9000000000289', 'botfrost5', 0, 52040, 166320, 760, 260, 6, 4, 3, 3),
    (293, 'playerbot_290', '9000000000290', 'botinferno5', 4, 52120, 166320, 760, 260, 6, 4, 3, 3),
    (294, 'playerbot_291', '9000000000291', 'botecho5', 1, 52200, 166320, 770, 260, 4, 3, 6, 3),
    (295, 'playerbot_292', '9000000000292', 'botspecter5', 5, 52280, 166320, 770, 260, 4, 3, 6, 3),
    (296, 'playerbot_293', '9000000000293', 'botdraco5', 2, 52360, 166320, 770, 300, 5, 3, 3, 5),
    (297, 'playerbot_294', '9000000000294', 'botsaber5', 6, 52440, 166320, 770, 300, 5, 3, 3, 5),
    (298, 'playerbot_295', '9000000000295', 'botfury5', 3, 52520, 166320, 860, 320, 3, 4, 3, 6),
    (299, 'playerbot_296', '9000000000296', 'botzenith5', 7, 52600, 166320, 860, 320, 3, 4, 3, 6),
    (300, 'playerbot_297', '9000000000297', 'botonyx5', 0, 52680, 166320, 760, 260, 6, 4, 3, 3),
    (301, 'playerbot_298', '9000000000298', 'botscarlet5', 4, 52760, 166320, 760, 260, 6, 4, 3, 3),
    (302, 'playerbot_299', '9000000000299', 'botsilver5', 1, 52840, 166320, 770, 260, 4, 3, 6, 3),
    (303, 'playerbot_300', '9000000000300', 'botamber5', 5, 52920, 166320, 770, 260, 4, 3, 6, 3),
    (304, 'playerbot_301', '9000000000301', 'botjade5', 2, 51000, 166440, 770, 300, 5, 3, 3, 5),
    (305, 'playerbot_302', '9000000000302', 'botcoral5', 6, 51080, 166440, 770, 300, 5, 3, 3, 5),
    (306, 'playerbot_303', '9000000000303', 'botflint5', 3, 51160, 166440, 860, 320, 3, 4, 3, 6),
    (307, 'playerbot_304', '9000000000304', 'botiron5', 7, 51240, 166440, 860, 320, 3, 4, 3, 6),
    (308, 'playerbot_305', '9000000000305', 'botsteel5', 0, 51320, 166440, 760, 260, 6, 4, 3, 3),
    (309, 'playerbot_306', '9000000000306', 'bottalon5', 4, 51400, 166440, 760, 260, 6, 4, 3, 3),
    (310, 'playerbot_307', '9000000000307', 'botfang5', 1, 51480, 166440, 770, 260, 4, 3, 6, 3),
    (311, 'playerbot_308', '9000000000308', 'botclaw5', 5, 51560, 166440, 770, 260, 4, 3, 6, 3),
    (312, 'playerbot_309', '9000000000309', 'bothawk5', 2, 51640, 166440, 770, 300, 5, 3, 3, 5),
    (313, 'playerbot_310', '9000000000310', 'botfalcon5', 6, 51720, 166440, 770, 300, 5, 3, 3, 5),
    (314, 'playerbot_311', '9000000000311', 'boteagle5', 3, 51800, 166440, 860, 320, 3, 4, 3, 6),
    (315, 'playerbot_312', '9000000000312', 'botwolf5', 7, 51880, 166440, 860, 320, 3, 4, 3, 6),
    (316, 'playerbot_313', '9000000000313', 'botlynx5', 0, 51960, 166440, 760, 260, 6, 4, 3, 3),
    (317, 'playerbot_314', '9000000000314', 'botpanther5', 4, 52040, 166440, 760, 260, 6, 4, 3, 3),
    (318, 'playerbot_315', '9000000000315', 'bottiger5', 1, 52120, 166440, 770, 260, 4, 3, 6, 3),
    (319, 'playerbot_316', '9000000000316', 'botbear5', 5, 52200, 166440, 770, 260, 4, 3, 6, 3),
    (320, 'playerbot_317', '9000000000317', 'botlion5', 2, 52280, 166440, 770, 300, 5, 3, 3, 5),
    (321, 'playerbot_318', '9000000000318', 'botcobra5', 6, 52360, 166440, 770, 300, 5, 3, 3, 5),
    (322, 'playerbot_319', '9000000000319', 'bothydra5', 3, 52440, 166440, 860, 320, 3, 4, 3, 6),
    (323, 'playerbot_320', '9000000000320', 'botchimera5', 7, 52520, 166440, 860, 320, 3, 4, 3, 6),
    (324, 'playerbot_321', '9000000000321', 'botdariusz6', 0, 52600, 166440, 760, 260, 6, 4, 3, 3),
    (325, 'playerbot_322', '9000000000322', 'botarek6', 4, 52680, 166440, 760, 260, 6, 4, 3, 3),
    (326, 'playerbot_323', '9000000000323', 'botbrutus6', 1, 52760, 166440, 770, 260, 4, 3, 6, 3),
    (327, 'playerbot_324', '9000000000324', 'botcien6', 5, 52840, 166440, 770, 260, 4, 3, 6, 3),
    (328, 'playerbot_325', '9000000000325', 'botluk6', 2, 52920, 166440, 770, 300, 5, 3, 3, 5),
    (329, 'playerbot_326', '9000000000326', 'botmrok6', 6, 51000, 166560, 770, 300, 5, 3, 3, 5),
    (330, 'playerbot_327', '9000000000327', 'botrunia6', 3, 51080, 166560, 860, 320, 3, 4, 3, 6),
    (331, 'playerbot_328', '9000000000328', 'botiskra6', 7, 51160, 166560, 860, 320, 3, 4, 3, 6),
    (332, 'playerbot_329', '9000000000329', 'botgrom6', 0, 51240, 166560, 760, 260, 6, 4, 3, 3),
    (333, 'playerbot_330', '9000000000330', 'botprobe6', 4, 51320, 166560, 760, 260, 6, 4, 3, 3),
    (334, 'playerbot_331', '9000000000331', 'botvalkyrie6', 1, 51400, 166560, 770, 260, 4, 3, 6, 3),
    (335, 'playerbot_332', '9000000000332', 'botshadow6', 5, 51480, 166560, 770, 260, 4, 3, 6, 3),
    (336, 'playerbot_333', '9000000000333', 'botviper6', 2, 51560, 166560, 770, 300, 5, 3, 3, 5),
    (337, 'playerbot_334', '9000000000334', 'botphantom6', 6, 51640, 166560, 770, 300, 5, 3, 3, 5),
    (338, 'playerbot_335', '9000000000335', 'botwitch6', 3, 51720, 166560, 860, 320, 3, 4, 3, 6),
    (339, 'playerbot_336', '9000000000336', 'botblaze6', 7, 51800, 166560, 860, 320, 3, 4, 3, 6),
    (340, 'playerbot_337', '9000000000337', 'botstorm6', 0, 51880, 166560, 760, 260, 6, 4, 3, 3),
    (341, 'playerbot_338', '9000000000338', 'bottitan6', 4, 51960, 166560, 760, 260, 6, 4, 3, 3),
    (342, 'playerbot_339', '9000000000339', 'botglory6', 1, 52040, 166560, 770, 260, 4, 3, 6, 3),
    (343, 'playerbot_340', '9000000000340', 'botghost6', 5, 52120, 166560, 770, 260, 4, 3, 6, 3),
    (344, 'playerbot_341', '9000000000341', 'botraven6', 2, 52200, 166560, 770, 300, 5, 3, 3, 5),
    (345, 'playerbot_342', '9000000000342', 'botabyss6', 6, 52280, 166560, 770, 300, 5, 3, 3, 5),
    (346, 'playerbot_343', '9000000000343', 'botmystic6', 3, 52360, 166560, 860, 320, 3, 4, 3, 6),
    (347, 'playerbot_344', '9000000000344', 'botoracle6', 7, 52440, 166560, 860, 320, 3, 4, 3, 6),
    (348, 'playerbot_345', '9000000000345', 'botsun6', 0, 52520, 166560, 760, 260, 6, 4, 3, 3),
    (349, 'playerbot_346', '9000000000346', 'botknight6', 4, 52600, 166560, 760, 260, 6, 4, 3, 3),
    (350, 'playerbot_347', '9000000000347', 'botblade6', 1, 52680, 166560, 770, 260, 4, 3, 6, 3),
    (351, 'playerbot_348', '9000000000348', 'botdusk6', 5, 52760, 166560, 770, 260, 4, 3, 6, 3),
    (352, 'playerbot_349', '9000000000349', 'botsilent6', 2, 52840, 166560, 770, 300, 5, 3, 3, 5),
    (353, 'playerbot_350', '9000000000350', 'botchaos6', 6, 52920, 166560, 770, 300, 5, 3, 3, 5);

DROP TEMPORARY TABLE IF EXISTS playerbot_seed_missing;
CREATE TEMPORARY TABLE playerbot_seed_missing LIKE playerbot_seed_spec;
INSERT INTO playerbot_seed_missing
SELECT s.*
FROM playerbot_seed_spec AS s
LEFT JOIN player.player AS p ON p.id = s.pid
WHERE p.id IS NULL;

DELIMITER //
BEGIN NOT ATOMIC
    DECLARE v_count INT DEFAULT 0;
    DECLARE v_min_pid INT DEFAULT 0;
    DECLARE v_max_pid INT DEFAULT 0;
    DECLARE v_conflicts INT DEFAULT 0;

    -- Validate the generated registry before examining or changing durable rows.
    SELECT COUNT(*), COALESCE(MIN(pid), 0), COALESCE(MAX(pid), 0)
      INTO v_count, v_min_pid, v_max_pid
      FROM playerbot_seed_spec;
    IF v_count <> 350 OR v_min_pid <> 4 OR v_max_pid <> 353 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed: registry is not exactly PID 4..353';
    END IF;

    -- A target PID may be reused only when its immutable identity is exact.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN player.player AS p ON p.id = s.pid
     WHERE BINARY p.name <> BINARY s.player_name OR p.job <> s.job;
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: target PID has a foreign name or job';
    END IF;

    -- player.name is only indexed, not unique, so detect aliases explicitly.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN player.player AS p ON p.name = s.player_name
     WHERE p.id <> s.pid;
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: expected name belongs to another PID';
    END IF;

    -- Existing bots must already belong to their canonical account. Password,
    -- status and all gameplay fields are deliberately not normalized on update.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN player.player AS p ON p.id = s.pid
      LEFT JOIN account.account AS a ON a.id = p.account_id
     WHERE a.id IS NULL
        OR BINARY a.login <> BINARY s.login
        OR BINARY a.social_id <> BINARY s.social_id;
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: existing PID has a foreign account';
    END IF;

    -- One bot account owns one character. Never attach a new bot to an account
    -- that already owns another character.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN account.account AS a ON a.login = s.login
      JOIN player.player AS p ON p.account_id = a.id
     WHERE p.id <> s.pid;
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: expected login owns another player';
    END IF;

    -- social_id has no UNIQUE constraint in the shipped schema.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN account.account AS a ON a.social_id = s.social_id
     WHERE BINARY a.login <> BINARY s.login;
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: social ID belongs to another login';
    END IF;

    -- A pre-existing account may be resumed for a missing PID only when it is
    -- unmistakably an unused partial result of this seed.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_missing AS s
      JOIN account.account AS a ON a.login = s.login
      LEFT JOIN player.player AS p ON p.account_id = a.id
      LEFT JOIN player.player_index AS pi ON pi.id = a.id
     WHERE BINARY a.login <> BINARY s.login
        OR BINARY a.social_id <> BINARY s.social_id
        OR BINARY a.password <> BINARY '!'
        OR BINARY a.status <> BINARY 'BLOCK'
        OR p.id IS NOT NULL
        OR pi.id IS NOT NULL;
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: missing PID account is foreign';
    END IF;

    -- Existing index rows may be absent (they will be added), or must be the
    -- exact one-character Chunjo index expected by the canonical account.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN player.player AS p ON p.id = s.pid
      JOIN account.account AS a ON a.id = p.account_id
      LEFT JOIN player.player_index AS pi ON pi.id = a.id
     WHERE pi.id IS NOT NULL
       AND (pi.pid1 <> s.pid OR pi.pid2 <> 0 OR pi.pid3 <> 0 OR pi.pid4 <> 0 OR pi.empire <> 2);
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: canonical account has a foreign index';
    END IF;

    -- Also reject a target PID referenced by any other/stale index slot.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN player.player_index AS pi
        ON s.pid IN (pi.pid1, pi.pid2, pi.pid3, pi.pid4)
      LEFT JOIN account.account AS a ON a.login = s.login
      LEFT JOIN player.player AS p ON p.id = s.pid
     WHERE p.id IS NULL
        OR a.id IS NULL
        OR pi.id <> a.id
        OR pi.pid1 <> s.pid
        OR pi.pid2 <> 0 OR pi.pid3 <> 0 OR pi.pid4 <> 0
        OR pi.empire <> 2;
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: target PID is in a foreign index';
    END IF;

    -- Only now is it safe to create durable migration metadata. MyISAM does
    -- not roll back, so this ledger lets an interrupted first seed finish only
    -- missing starter slots. Adopted/complete bots are never restocked.
    CREATE TABLE IF NOT EXISTS common.playerbot_seed_state (
        pid          INT UNSIGNED NOT NULL,
        seed_version SMALLINT UNSIGNED NOT NULL,
        state        ENUM('pending','complete','adopted') NOT NULL,
        updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                     ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (pid)
    ) ENGINE=MyISAM DEFAULT CHARSET=ascii;

    -- Ledger rows from another seed version, or completed rows whose player is
    -- gone, are ambiguous and must be repaired by an operator rather than guessed.
    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_spec AS s
      JOIN common.playerbot_seed_state AS l ON l.pid = s.pid
      LEFT JOIN player.player AS p ON p.id = s.pid
     WHERE l.seed_version <> 1
        OR (p.id IS NULL AND l.state IN ('complete', 'adopted'));
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed conflict: ledger conflicts with player data';
    END IF;

    -- Mark every previously unseen row before touching MyISAM account/player
    -- data. A crash from here on leaves a resumable pending marker.
    INSERT INTO common.playerbot_seed_state (pid, seed_version, state)
    SELECT s.pid, 1, IF(p.id IS NULL, 'pending', 'adopted')
      FROM playerbot_seed_spec AS s
      LEFT JOIN player.player AS p ON p.id = s.pid
      LEFT JOIN common.playerbot_seed_state AS l ON l.pid = s.pid
     WHERE l.pid IS NULL;

    INSERT INTO account.account
        (login, password, social_id, email, create_time, is_testor, status,
         empire, name_checked, availDt, last_play)
    SELECT s.login, '!', s.social_id, '', UTC_TIMESTAMP(), 0, 'BLOCK',
           2, 1, UTC_TIMESTAMP(), UTC_TIMESTAMP()
      FROM playerbot_seed_missing AS s
      JOIN common.playerbot_seed_state AS l ON l.pid = s.pid AND l.state = 'pending'
      LEFT JOIN account.account AS a ON a.login = s.login
     WHERE a.id IS NULL;

    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_missing AS s
      LEFT JOIN account.account AS a ON a.login = s.login
     WHERE a.id IS NULL
        OR BINARY a.login <> BINARY s.login
        OR BINARY a.social_id <> BINARY s.social_id
        OR BINARY a.password <> BINARY '!'
        OR BINARY a.status <> BINARY 'BLOCK';
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed: failed to create blocked bot accounts';
    END IF;

    INSERT INTO player.player
        (id, account_id, name, job, voice, dir, x, y, z, map_index,
         exit_x, exit_y, exit_map_index, hp, mp, stamina, level, level_step,
         st, ht, dx, iq, exp, gold, stat_point, skill_point, skill_group,
         sub_skill_point, stat_reset_count, horse_hp, horse_stamina,
         horse_level, horse_hp_droptime, horse_riding, horse_skill_point,
         bank_value, last_play)
    SELECT s.pid, a.id, s.player_name, s.job, 0, 0, s.x, s.y, 0, 21,
           s.x, s.y, 21, s.hp, s.mp, 800, 1, 0,
           s.st, s.ht, s.dx, s.iq, 0, 2500, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, UTC_TIMESTAMP()
      FROM playerbot_seed_missing AS s
      JOIN account.account AS a ON a.login = s.login
      JOIN common.playerbot_seed_state AS l ON l.pid = s.pid AND l.state = 'pending'
      LEFT JOIN player.player AS p ON p.id = s.pid
     WHERE p.id IS NULL;

    -- Adding a genuinely missing index is safe for adopted bots as well; no
    -- existing row is ever updated or reassigned.
    INSERT INTO player.player_index (id, pid1, pid2, pid3, pid4, empire)
    SELECT a.id, s.pid, 0, 0, 0, 2
      FROM playerbot_seed_spec AS s
      JOIN player.player AS p
        ON p.id = s.pid AND BINARY p.name = BINARY s.player_name AND p.job = s.job
      JOIN account.account AS a
        ON a.id = p.account_id
       AND BINARY a.login = BINARY s.login
       AND BINARY a.social_id = BINARY s.social_id
      LEFT JOIN player.player_index AS pi ON pi.id = a.id
     WHERE pi.id IS NULL;

    DROP TEMPORARY TABLE IF EXISTS playerbot_seed_pending;
    CREATE TEMPORARY TABLE playerbot_seed_pending (
        pid INT UNSIGNED NOT NULL PRIMARY KEY
    ) ENGINE=MEMORY;
    INSERT INTO playerbot_seed_pending (pid)
    SELECT s.pid
      FROM playerbot_seed_spec AS s
      JOIN common.playerbot_seed_state AS l ON l.pid = s.pid
     WHERE l.state = 'pending';

    -- Only pending (new or interrupted) bots receive starter slots. An occupied
    -- slot is preserved, regardless of which item is already there.
    INSERT INTO player.item (owner_id, window, pos, count, vnum)
    SELECT s.pid, 'EQUIPMENT', 4, 1,
           CASE
             WHEN s.job IN (0, 2, 4, 6) THEN 10
             WHEN s.job IN (1, 5) THEN 1000
             WHEN s.job IN (3, 7) THEN 7000
           END
      FROM playerbot_seed_spec AS s
      JOIN playerbot_seed_pending AS q ON q.pid = s.pid
      LEFT JOIN player.item AS i
        ON i.owner_id = s.pid AND i.window = 'EQUIPMENT' AND i.pos = 4
     WHERE i.id IS NULL;

    INSERT INTO player.item (owner_id, window, pos, count, vnum)
    SELECT s.pid, 'EQUIPMENT', 0, 1,
           CASE
             WHEN s.job IN (0, 4) THEN 11200
             WHEN s.job IN (1, 5) THEN 11400
             WHEN s.job IN (2, 6) THEN 11600
             WHEN s.job IN (3, 7) THEN 11800
           END
      FROM playerbot_seed_spec AS s
      JOIN playerbot_seed_pending AS q ON q.pid = s.pid
      LEFT JOIN player.item AS i
        ON i.owner_id = s.pid AND i.window = 'EQUIPMENT' AND i.pos = 0
     WHERE i.id IS NULL;

    INSERT INTO player.item (owner_id, window, pos, count, vnum)
    SELECT s.pid, 'INVENTORY', 0, 200, 27001
      FROM playerbot_seed_spec AS s
      JOIN playerbot_seed_pending AS q ON q.pid = s.pid
      LEFT JOIN player.item AS i
        ON i.owner_id = s.pid AND i.window = 'INVENTORY' AND i.pos = 0
     WHERE i.id IS NULL;

    INSERT INTO player.item (owner_id, window, pos, count, vnum)
    SELECT s.pid, 'INVENTORY', 1, 200, 27004
      FROM playerbot_seed_spec AS s
      JOIN playerbot_seed_pending AS q ON q.pid = s.pid
      LEFT JOIN player.item AS i
        ON i.owner_id = s.pid AND i.window = 'INVENTORY' AND i.pos = 1
     WHERE i.id IS NULL;

    INSERT INTO player.item (owner_id, window, pos, count, vnum)
    SELECT s.pid, 'INVENTORY', 2, 1,
           CASE
             WHEN s.job IN (0, 2, 4, 6) THEN 50187
             WHEN s.job IN (1, 5) THEN 50212
             WHEN s.job IN (3, 7) THEN 50213
           END
      FROM playerbot_seed_spec AS s
      JOIN playerbot_seed_pending AS q ON q.pid = s.pid
      LEFT JOIN player.item AS i
        ON i.owner_id = s.pid AND i.window = 'INVENTORY' AND i.pos = 2
     WHERE i.id IS NULL;

    -- The seed already supplied the starter chest above. Mark the stock login
    -- reward as claimed so give_basic_weapon does not create a second chest and,
    -- transitively, duplicate every later Apprentice/Expert chest.
    INSERT INTO player.quest (dwPID, szName, szState, lValue)
    SELECT q.pid, 'give_basic_weapon', 'basic_weapon', 1
      FROM playerbot_seed_pending AS q
    ON DUPLICATE KEY UPDATE lValue = GREATEST(lValue, VALUES(lValue));

    SELECT COUNT(*) INTO v_conflicts
      FROM playerbot_seed_pending AS q
     WHERE NOT EXISTS (
               SELECT 1 FROM player.item AS i
                WHERE i.owner_id = q.pid AND i.window = 'EQUIPMENT' AND i.pos = 4)
        OR NOT EXISTS (
               SELECT 1 FROM player.item AS i
                WHERE i.owner_id = q.pid AND i.window = 'EQUIPMENT' AND i.pos = 0)
        OR NOT EXISTS (
               SELECT 1 FROM player.item AS i
                WHERE i.owner_id = q.pid AND i.window = 'INVENTORY' AND i.pos = 0)
        OR NOT EXISTS (
               SELECT 1 FROM player.item AS i
                WHERE i.owner_id = q.pid AND i.window = 'INVENTORY' AND i.pos = 1)
        OR NOT EXISTS (
               SELECT 1 FROM player.item AS i
                WHERE i.owner_id = q.pid AND i.window = 'INVENTORY' AND i.pos = 2);
    IF v_conflicts <> 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed: starter slots are incomplete';
    END IF;

    UPDATE common.playerbot_seed_state AS l
      JOIN playerbot_seed_pending AS q ON q.pid = l.pid
       SET l.state = 'complete', l.seed_version = 1;

    -- Final structural assertion; this intentionally does not compare level,
    -- position, skills, horse, quests, gold or items of adopted bots.
    SELECT COUNT(*) INTO v_count
      FROM playerbot_seed_spec AS s
      JOIN player.player AS p
        ON p.id = s.pid AND BINARY p.name = BINARY s.player_name AND p.job = s.job
      JOIN account.account AS a
        ON a.id = p.account_id
       AND BINARY a.login = BINARY s.login
       AND BINARY a.social_id = BINARY s.social_id
      JOIN player.player_index AS pi
        ON pi.id = a.id AND pi.pid1 = s.pid
       AND pi.pid2 = 0 AND pi.pid3 = 0 AND pi.pid4 = 0 AND pi.empire = 2
      JOIN common.playerbot_seed_state AS l
        ON l.pid = s.pid AND l.seed_version = 1
       AND l.state IN ('complete', 'adopted');
    IF v_count <> 350 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'playerbot seed: final 350-row assertion failed';
    END IF;
END//
DELIMITER ;

DROP TEMPORARY TABLE IF EXISTS playerbot_seed_pending;
DROP TEMPORARY TABLE IF EXISTS playerbot_seed_missing;
DROP TEMPORARY TABLE IF EXISTS playerbot_seed_spec;
